### ISSUE TITLE
ModuleNotFoundError: No module named 'applitools.selenium'; 

### ISSUE THREAD

**Issue by suvasishmanna** [applitools/eyes.sdk.python#104]
Hello!!

I was trying to connect Applitools using the recommended way mentioned in https://applitools.com/tutorials/selenium-python.html. But facing a module not found error as mentioned below. 

**Code snippet giving error:**
```
from applitools.selenium import Eyes
from applitools.common import StitchMode
from applitools.eyes import BatchInfo
```

**Actual Error Message**
```
from applitools.selenium import Eyes
ModuleNotFoundError: No module named 'applitools.selenium'; 'applitools' is not a package
```

**System Configurations**
```
Operating System => Mac - IOS 10.15.3
Python version => 3.6.1
Already installed the SDK using "pip3 install eyes-selenium"
```

Please let me know if Im doing something wrong  or you need any other details.

**Comment by Infernion** [comment]
Hi @suvasishmanna!

Have you tried install everything inside virtualenv and run from there?

**Comment by danielputerman** [comment]
@suvasishmanna If this is still an issue for you,  please refer such question to Applitools support:
support [at] applitools.com
