### ISSUE TITLE
UserWarning: DEPRECATION: Use `abort()` instead   warnings.warn("DEPRECATION: {}".format(msg))

### ISSUE THREAD

**Issue by lwazi2018** [applitools/eyes.sdk.python#119]
Hi team can someone help me with the above error.
my code can open an installed app and see login form, from that login I want to `eyes.check_window('Login form')` my code stops here it can't go past line of code
below is my code:
`eyes = Eyes()
        eyes.api_key = 'my key'
        self.driver.implicitly_wait(10)
        eyes.open(self.driver, app_name = 'Shyft', test_name = 'Login test')

        el = self.driver.find_element_by_id("skip_landing")
        el.click()
        eyes.check_window('Login Screen')
# can't run the following code

        login_email = self.driver.find_element_by_id("login_email")
        login_email.send_keys('my email')`

**Comment by danielputerman** [comment]
Hi @lwazi2018, for such questions please contact Applitools support: support [at] applitools.com
