### ISSUE TITLE
ImportError: cannot import name 'Region'

### ISSUE THREAD

**Issue by Bharath369-hub** [applitools/eyes.sdk.python#234]
from applitools.core import Region throws the import error. Is this method deprecated or moved to any other library?

**Comment by skhalymon** [comment]
Hi @Bharath369-hub!

Have you tried to import Region from `applitools.common` or `applitools.selenium`?

**Comment by Bharath369-hub** [comment]
Tried` applitools.common` now. Region is available. I got `from applitools.core import Region` from one of applitool documentation for screenshot sdk. would ` from applitools.common import Region ` work in my case where i want to upload images?

**Comment by skhalymon** [comment]
Could you give a link to documentation where you've found it? @yonatanLehman would check it out.

If you want to use Region for images you could import it both from `applitools.common` and `applitools.images`. It's a shortcut.

**Comment by Bharath369-hub** [comment]
https://applitools.com/tutorials/screenshots-python.html#analyze-your-test-results

**Comment by skhalymon** [comment]
Thanks @Bharath369-hub !

**Comment by skhalymon** [comment]
The tutorial is updated now
