### ISSUE TITLE
Don't pin upper limits to setup.py required packages

### ISSUE THREAD

**Issue by Dude-X** [applitools/eyes.sdk.python#24]
For each python package `eyes-common`, `eyes-selenium`, `eyes-core`, I would like it if setup.py doesn't pin an upper limit to the required packages.

It is annoying to see warnings about libraries being outside the required range.

**Comment by Infernion** [comment]
Would be ok if we would pin to minor version instead?

**Comment by Infernion** [comment]
@Dude-X for now, it's not possible. Packages are pinned, in such a way, because of support Python 2

**Comment by Dude-X** [comment]
It's a minor nit, but for now we can override with requirements.txt.
