### ISSUE TITLE
eyes_robotframework: Documentation: Add blank line to keyword docstring to cleanup tooltips

### ISSUE THREAD

**Issue by emanlove** [applitools/eyes.sdk.python#380]
Within the keyword documentation if one hovers the mouse over a keyword name in the left hand (under LTR locales) list the keyword tooltip is long and contains both the short description and the arguments table markdown. Reviewing another library I see robot takes up to the first blank line as the tooltip.

For example if the [docstring on the accessibility_region_by_element keyword](https://github.com/applitools/eyes.sdk.python/blob/05e83446a1ffb637eb204918e69e9c1ec43a7759/eyes_robotframework/src/EyesLibrary/keywords/check_settings.py#L498) changes to 

```python
        """
        Returns a CheckSettings object with accessibility region specified in the arguments.

            | =Arguments=      | =Description=                                                            |
            | Element          | *Mandatory* - The accessibility region e.g. [100 200 300 300]                                                             |
            | Type             | *Mandatory* - Type of AccessibilityRegion. (`IgnoreContrast`, `RegularText`, `LargeText`, `BoldText`, `GraphicalObject`)  |

...
        """
```
noting the blank line after `Returns a CheckSettings object with accessibility region specified in the arguments.` this resolves the tooltip issue.

For reference one can see the [Click Element keyword documentation](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Click%20Element) and it's tooltip along with the [docstring for the keyword](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/keywords/element.py#L623).

This may also resolve the issue reported about using the Robotframework LSP and code completion.

**Comment by skhalymon** [comment]
Hi @emanlove ! Thanks for this advice!
