### ISSUE TITLE
eyes_robotframework: Documentation: Use "Ultrafast Grid" instead of UFG

### ISSUE THREAD

**Issue by emanlove** [applitools/eyes.sdk.python#381]
It is recommended that documentation uses the full term instead of acronyms if your target audience is learning the subject matter presented. I came across the acronym "UFG" first in the keyword tags and unfamiliar with this acronym searched the applitools doc. There is [no usage of "UFG"](https://applitools.com/docs/searchresults.html?q=UFG) in the docs. [Searching the main applitools.com website](https://applitools.com/?ss360Query=UFG) there I found some references to "UFG" and, although still somewhat obscure, I was able to realize this was something called "Ultrafast Grid". Then I was able to search some more to see what Ultrafast grid was.

So in general its best not to use acronyms in documentation.

**Comment by emanlove** [comment]
I should add I see no problems using UFG internally in the code nor external in for example the setting web_ufg. This recommendation is more for documentation then code or settings.

**Comment by skhalymon** [comment]
Hi @emanlove ! Thanks for this advice too!
