### ISSUE TITLE
Support Selenium >v4.0 and Appium Python Client > v2.0

### ISSUE THREAD

**Issue by rkavalap** [applitools/eyes.sdk.python#395]
Support Selenium >v4.0 and Appium Python Client > v2.0

https://github.com/applitools/eyes.sdk.python/blob/22b76f712a312132aef4fddabae6c78779517bd4/eyes_selenium/setup.py#L29
https://github.com/applitools/eyes.sdk.python/blob/22b76f712a312132aef4fddabae6c78779517bd4/eyes_selenium/setup.py#L45

**Comment by ikseek** [comment]
Selenium 4 and Appium 2 are supported by eyes-selenium 5.0.0 (Selenium 4 requires python 3.7)
