### ISSUE TITLE
No module named "applitools.common" python3

### ISSUE THREAD

**Issue by technigirl** [applitools/eyes.sdk.python#55]
I am having an issue running the applitools demo on python 3.  I have installed using "pip3 install eyes-selenium", but when I run the tutorial.py, I get the following error:

Traceback (most recent call last):
  File "tutorial.py", line 2, in <module>
    from applitools.selenium import Eyes, Target
  File "/usr/local/lib/python3.7/site-packages/applitools/selenium/__init__.py", line 1, in <module>
    from applitools.common import (  # noqa
ModuleNotFoundError: No module named 'applitools.common'

Interestingly, I also did the installation on python 2.7 on this same machine, and the tutorial runs with no issues.  Issue seems to be only with python 3.

I am using this tutorial: https://applitools.com/tutorials/selenium-python.html
I am running this on MacOS Mojave.
I have tried uninstalling/re-installing several times to no avail.
I really need to run this on Python 3, would appreciate any help.  Thanks!

**Comment by Infernion** [comment]
Hi @technigirl ! Could you try to fresh install inside virtualenv? Or to be sure that you use correct version of pip you could run `python3 -m pip install -U eyes-selenium`.

**Comment by technigirl** [comment]
Hi @Infernion , I was able to resolve the issue by downloading the repo and running setup.py on eyes-common, eyes-core, and eyes-selenium.  Now the tutorial runs fine for me using python3.  I do have an appointment with a technical support person to investigate the pip installation issue though.  Not sure if we will be able to root cause it now that it works, but they wanted to try.  :)
